"""Add edit and delete features

Revision ID: 3b1ea7a692df
Revises: f8904e18d688
Create Date: 2026-07-11 15:17:41.210924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1ea7a692df'
down_revision: Union[str, Sequence[str], None] = 'f8904e18d688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_user_emoji')
    )
    op.create_index('ix_message_reactions_message_id', 'message_reactions', ['message_id'], unique=False)
    op.create_table('user_message_deletions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_user_message_deletion')
    )
    op.create_index('ix_user_msg_del_user_id', 'user_message_deletions', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'updated_at')
    op.drop_index('ix_user_msg_del_user_id', table_name='user_message_deletions')
    op.drop_table('user_message_deletions')
    op.drop_index('ix_message_reactions_message_id', table_name='message_reactions')
    op.drop_table('message_reactions')
    # ### end Alembic commands ###
